config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get '/home', to: 'pages#home'

  # get    '/recipes', to: 'recipes#index'
  # get    '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  # post   '/recipes', to: 'recipes#create'
  # get    '/recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
  # patch  '/recipes/:id', to: 'recipes#update'
  # get    '/recipes/:id', to: 'recipes#show', as: 'recipe'
  # delete 'recipes/:id', to: 'recipes#destroy'
  resources :recipes do
    member do
     post 'like'
    end
  end

  resources :chefs, except: [:new, :destroy]

  get '/register', to: 'chefs#new'


  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'

  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]

end

app/views/pages/home.html.erb
<div class = "center jumbotron blend-reef">
    <h1>Welcome to GREAT RECIPES</h1>
    <h3>This is the home page for the Professional Ruby on Rails Developer Course</h3>
    <%= link_to "Sign up now!", register_path, class: 'btn btn-default gradient btn-lg' %>
</div>

<div class = "row">
  <div class = "col-lg-4 center">
    <h4 class = "midrow">
      View Recipes as Guest User
    </h4>
    <h4 class = "center">
      Browse and view recipes as a guest and Sign up later.</h4>
      <p><%= link_to "Browse recipes listings", recipes_path, class: 'btn btn-primary gradient' %></p>
  </div>
  <div class = "col-lg-4 center">
    <h4 class = "midrow">
     Sign in to your Account
    </h4>
    <h4 class = "center">Add or update your recipes.  Create reviews.  Like or Dislike Recipes</h4>
      <p><%= link_to "Login to your Account", login_path , class: 'btn btn-default gradient' %></p>
  </div>
  <div class = "col-lg-4 center">
    <h4 class = "midrow">
      View Recipes as Guest User
    </h4>
    <h4 class = "center">
      Browse and view recipes as a guest and Sign up later.</h4>
      <p><%= link_to "Browse recipes listings", "", class: "btn btn-primary gradient" %></p>
  </div>
</div>